export const films = [
    {
      id: 1,
      title: "Star Wars: Episode I - The Phantom Menace",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/C738C29A957035D7109132F2864962B10E32314C74517C591AA99BA4189C3EFD/scale?width=1200&aspectRatio=1.78&format=jpeg",
      detailPhoto: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/8B7D915060B93EF47386299C26517DE844FF2146556BBB4713D2408448ECAF7C/scale?width=1440&aspectRatio=1.78&format=png",
      background:"https://images8.alphacoders.com/983/983156.jpg",
      tags: "1999 ‧ Sci-fi/Action ‧ 2h 16m ",
      description:"Two Jedi escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force, but the long dormant Sith resurface to claim their original glory.",
      plot:`The film takes place 32 years before the events of the original "Star Wars" film, and follows Jedi Knights Qui-Gon Jinn and Obi-Wan Kenobi as they protect Queen Amidala and her planet from the evil Trade Federation. Along the way, they meet a young slave named Anakin Skywalker who may be the chosen one to bring balance to the Force.`,
      trailer: "https://www.youtube.com/watch?v=bD7bpG-zDJQ&t=2s",
      duration:"2h 16m",
      releaseDate: "1999",
      genre: "Sci-fi/Action",
      director:"George Lucas",
      starring:"Liam Neeson, Ewan McGregor, Natalie Portman, Jake Lloyd, Pernilla August, Frank Oz",
      category: "StarWars" ,
      
     
     
      
    },
    {
      id: 16 ,
      title: "Star Wars: Episode II - Attack of the Clones",
      image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/EA545D0F238ADD340517DBE4344899EC16F73C60D5DD8FE20C9B1D2D19AF6392/scale?width=400&aspectRatio=1.78&format=jpeg",
      detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/329AEF28993DAD9D32D1CD84D9FFB6D674C765EB7099C950D975A1825A76F11F/scale?width=1440&aspectRatio=1.78&format=png",
      background:"https://wallpapermemory.com/uploads/339/star-wars-episode-2-ii-attack-of-the-clones-wallpaper-full-hd-1920x1080-194114.jpg",
      tags: " 2002 ‧ Sci-fi/Action ‧ 2h 22m ",
      plot:`Star Wars: Episode II - Attack of the Clones is a 2002 American epic space opera film directed by George Lucas and written by Lucas and Jonathan Hales. The sequel to The Phantom Menace (1999), it is the fifth film in the Star Wars film series and second chronological chapter of the "Skywalker Saga". The film stars Ewan McGregor, Natalie Portman, Hayden Christensen, Ian McDiarmid, Samuel L. Jackson, Christopher Lee, Anthony Daniels, Kenny Baker, Frank Oz, Temuera Morrison, Silas Carson and Jimmy Smits.
      The story is set ten years after The Phantom Menace, as thousands of planetary systems slowly secede from the Galactic Republic and join the newly-formed Confederacy of Independent Systems, led by former Jedi Master Count Dooku. With the galaxy on the brink of civil war, Obi-Wan Kenobi investigates a mysterious assassination attempt on Senator Padmé Amidala, which leads him to uncover a clone army in service of the Republic and the truth behind the Separatist movement. Meanwhile, his apprentice Anakin Skywalker is assigned to protect Amidala and develops a secret relationship with her. Soon, the trio witness the onset of a new threat to the galaxy: the Clone Wars.`,
      description:"Ten years after initially meeting, Anakin Skywalker shares a forbidden romance with Padmé Amidala, while Obi-Wan Kenobi investigates an assassination attempt on the senator and discovers a secret clone army crafted for the Jedi",
      trailer: "https://www.youtube.com/watch?v=gYbW1F_c9eM",
      duration:"2h 22m",
      releaseDate: "2002",
      genre: "Sci-fi/Action",
      director:"George Lucas",
      starring:"	Ewan McGregorNatalie Portman Hayden Christensen Ian McDiarmid Samuel L. Jackson Christopher Lee Anthony Daniels Kenny Baker Frank Oz ",
      category: "StarWars" ,
    },
    {
      id:3 ,
      title: "Star Wars: Episode III - Revenge of the Sith",
      detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/8276B5D2B7D4DE64DC7D64DBD55D3D7D665669D02B7DDD1865BAFF6E16AAB112/scale?width=1440&aspectRatio=1.78&format=png",
      background:"https://rare-gallery.com/uploads/posts/549139-star-wars-star.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/8E45ABC57042AF80094DA193EA2FE089173703BBFBB853C490A1422324788D62/scale?width=1200&aspectRatio=1.78&format=jpeg ",
      tags: "2005 ‧ Action/Sci-fi ‧ 2h 20m ",
      plot:"It has been three years since the Clone Wars began. Jedi Master Obi-Wan Kenobi (Ewan McGregor) and Jedi Knight Anakin Skywalker (Hayden Christensen) rescue Chancellor Palpatine (Ian McDiarmid) from General Grievous, the commander of the droid armies, but Grievous escapes. Suspicions are raised within the Jedi Council concerning Chancellor Palpatine, with whom Anakin has formed a bond. Asked to spy on the chancellor, and full of bitterness toward the Jedi Council, Anakin embraces the Dark Side.",
      description:"Three years into the Clone Wars, the Jedi rescue Palpatine from Count Dooku. As Obi-Wan pursues a new threat, Anakin acts as a double agent between the Jedi Council and Palpatine and is lured into a sinister plan to rule the galaxy.",
      trailer: "https://www.youtube.com/watch?v=5UnjrG_N8hU",
      duration:"2h 20m",
      releaseDate: "2005",
      genre: "Action/Sci-fi",
      director:"George Lucas",
      starring:"	Ewan McGregor Natalie Portman Hayden Christensen Ian McDiarmid Samuel L. Jackson Christopher Lee Anthony Daniels Kenny Baker Frank Oz",
      category: "StarWars" ,
      recommended: true,
    },
    {
      id:4 ,
      title: "Star Wars: Episode IV - A New Hope",
      detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/114FE8446CC765504D401A6D1F97AFE2F8E21085CA5D09213345053DF71A0893/scale?width=1440&aspectRatio=1.78&format=png",
      background:"https://images6.alphacoders.com/613/thumb-1920-613328.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/78A138B561F468B457EEA22AB20C3C30772D1070DA64575B95C5B27B1EB9E17B/scale?width=800&aspectRatio=1.78&format=jpeg ",
      tags: " 1977 ‧ Sci-fi ‧ 2h 1m ",
      plot:"Far off in a distant galaxy, the starship belonging to Princess Leia, a young member of the Imperial Senate, is intercepted in the course of a secret mission by a massive Imperial Star Destroyer. An imperial boarding party blasts its way onto the captured vessel, and after a fierce firefight the crew of Leia’s ship is subdued. The dark, forbidding figure of Darth Vader appears, brutally interrogating the crew and ordering his stormtroopers to search the ship for the secret documents he believes it is carrying: the technical readouts for the Empire’s mightiest weapon—a planet-sized battle station called the Death Star. In the confusion, Princess Leia slips away and hides the secret documents, as well as a recorded plea for help, in the memory of R2-D2, a maintenance droid (robot). Leia is taken prisoner, but R2 gets away in an escape pod, along with his best friend, the protocol droid C-3PO. After crash-landing on the planet below, a barren, desert world called Tatooine, the droids set off in search of civilization but soon quarrel over the way to go. R2 insists that he has a mission to perform, but C-3PO wants no part of such an adventure",
      duration:"2h 1m",
      releaseDate: " 1977 ",
      genre: "Sci-fi",
      director:"George Lucas",
      starring:" Mark Hamill, Harrison Ford, Carrie Fisher, Alec Guiness, James Earl Jones",
      description:"Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
      trailer: "https://www.youtube.com/watch?v=vZ734NWnAHA",
      category: "StarWars" ,
    },
    {
      id:5 ,
      title: "Star Wars: Episode V - The Empire Strikes Back",
      detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/EEB7F9279E013A51BD73403D62960C3C96FD1CFE2518E10CF2F12391D01472BC/scale?width=1440&aspectRatio=1.78&format=png",
      background:"https://rare-gallery.com/mocahbig/77814-Star-WarsStar-Wars-Episode-V-The-Empire-Strikes-Back.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/9B5F5B3695F760B39713902E6C1D27893F5C45AA66B424516F8342515468536B/scale?width=800&aspectRatio=1.78&format=jpeg",
      tags: " 1980 ‧ Sci-fi/Adventure ‧ 2h 4m",
      plot:"After the destruction of the Death Star, Imperial forces continue to pursue the Rebels. After the Rebellion’s defeat on the ice planet Hoth, Luke journeys to the planet Dagobah to train with Jedi Master Yoda, who has lived in hiding since the fall of the Republic. In an attempt to convert Luke to the dark side, Darth Vader lures young Skywalker into a trap in the Cloud City of Bespin.",
      duration:"2h 4m",
      releaseDate: "1980",
      genre: "Sci-fi/Adventure",
      director:" George Lucas",
      starring:"Mark Hamill, Harrison Ford, Carrie Fisher, Alec Guiness, James Earl Jones, Billy Dee Williams",
      description:"After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.",
      trailer: "https://www.youtube.com/watch?v=JNwNXF9Y6kY",
      category: "StarWars" ,
      recommended: true,
    },
    {
      id:6 ,
      title: "Star Wars: Episode VI - Return of the Jedi",
      detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/D395E777111669996DFAA18F186BF76DEBEAFF085869D0DD8CB4E158F1ACA64C/scale?width=1440&aspectRatio=1.78&format=png",
      background:"https://img3.goodfon.com/wallpaper/nbig/f/92/star-wars-episode-vi---return.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/C6D2C704254F71B2DF415A48F653F769FF10900D05C3146A6E5CFF5C6BDA1AF1/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: " 1983 ‧ Sci-fi/Action ‧ 2h 11m ",
      plot:"After a quick trip back to Tatooine, Luke Skywalker, Leia Organa, and Han Solo are reunited and join up with the amassing rebel fleet to take down the evil Empire once and for all. But the Empire is plotting too. Emperor Palpatine commands his troops aboard his newly consturcted Death Star stationed above the forest moon of Endor, where the rebels - and some unlikely furry friends - make their stand against the Empire. While Luke Skywalker confronts Darth Vader on the Death Star once more, Han leads a team to take out a shield protecting the battle station so that the rebel fleet can destory it once more and finally put an end to the war...",
      duration:"2h 11m",
      releaseDate: "1983",
      genre: "Action, Adventure, Fantasy, Live Action, Science Fiction",
      director:"George Lucas",
      starring:"Mark Hamill, Harrison Ford, Carrie Fisher, Alec Guiness, James Earl Jones, Billy Dee Williams",
      description:"After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star. Meanwhile, Luke struggles to help Darth Vader back from the dark side without falling into the Emperor's trap.",
      trailer: "https://www.youtube.com/watch?v=XgB4gaY2dWE",
      category: "StarWars" ,
    },
    {
      id:20 ,
      title: "Star Wars: Episode VII - The Force Awakens",
      detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/FA7412E35D1A05DC632F2406E05BD2CD641E7A330C4AB2D0AA902E98806995F0/scale?width=1440&aspectRatio=1.78&format=png",
      background:"https://whatsondisneyplus.com/wp-content/uploads/2019/10/force-awakens-e1570528179432.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/CF05493C681BE56C7D085E1131EE47D12D9BC505411E1D77BB2164D84AE0CC48/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: "2015 ‧ Sci-fi/Action ‧ 2h 16m",
      plot:"Thirty years since the destruction of the second Death Star, the sinister First Order, commanded by the mysterious Snoke and apprentice Kylo Ren, rise from the ashes of the Empire. The Resistance, led by General Leia Organa, attempts to thwart the First Order's threat, but they're desparate for help. Rey, a desert scavenger, and Finn, an ex-stormtrooper, find themselves joining forces wiiht Han Solo and Chewbacca in a desperate mission to return a BB-unit droid with a map to Luke Skywalker back to the Resistance",
      duration:"2h 16m",
      releaseDate: "2015",
      genre: "Sci-fi/Action",
      director:"J.J Abrams",
      starring:"Daisy Ridley, John Boyega, Adam Driver, Harrison Ford, Oscar Isaac, Carrie Fisher",
      description:"As a new threat to the galaxy rises, Rey, a desert scavenger, and Finn, an ex-stormtrooper, must join Han Solo and Chewbacca to search for the one hope of restoring peace.",
      trailer: "https://www.youtube.com/watch?v=sGbxmsDFVnE",
      category: "StarWars" ,
    },
    {
      id:8 ,
      title: "Star Wars: Episode VIII - The Last Jedi",
      detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/68CFAAE4A5521D8892DE8A254804BE3AEC035EF23BB8FBF316EC7FF6D4584C64/scale?width=1440&aspectRatio=1.78&format=png",
      background:"https://cdn.mos.cms.futurecdn.net/vzatcJE9V7Kk3ktbY5wwJD.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/09B5E23DC281415A7B14D33D4EA08D52A4E74AD6FCB9E6C9FC604AF6910054F4/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: "2017 ‧ Sci-fi/Action ‧ 2h 32m",
      plot:"Luke Skywalker's peaceful and solitary existence gets upended when he encounters Rey, a young woman who shows strong signs of the Force. Her desire to learn the ways of the Jedi forces Luke to make a decision that changes their lives forever. Meanwhile, Kylo Ren and General Hux lead the First Order in an all-out assault against Leia and the Resistance for supremacy of the galaxy.",
      duration:"2h 32m",
      releaseDate: " 2017 ",
      genre: "Sci-fi/Action",
      director:"Rian Johnson",
      starring:"Daisy Ridley, John Boyega, Adam Driver, Oscar Isaac, Mark Hamill, Carrie Fisher, Gwendoline Christie, Laura Dern",
      description:"The Star Wars saga continues as new heroes and galactic legends go on an epic adventure, unlocking mysteries of the Force and shocking revelations of the past",
      trailer: "https://www.youtube.com/watch?v=Q0CbN8sfihY",
      category: "StarWars" ,
    },
    {
      id:9 ,
      title: "Star Wars: Episode IX - The Rise of Skywalker",
      detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/7896EC8D4A4A8545B1738873F8BD7C3F0F2CB476826F75C4BA39F34A609B617E/scale?width=1440&aspectRatio=1.78&format=png",
      background:"https://whatsondisneyplus.com/wp-content/uploads/2019/12/rise-of-skywlkaer.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/57805B4A4CB382D4737B65339AC37B433AAF052C21726B2EB40D1088151BED1E/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: "2019 ‧ Sci-fi/Action  ‧ 2h 21m ",
      plot:"The Rise of Skywalker follows Rey, Finn, and Poe Dameron as they lead the Resistance's final stand against Supreme Leader Kylo Ren and the First Order, who are aided by the return of the Galactic Emperor, Palpatine.",
      duration:"2h 21m",
      releaseDate: "2019",
      genre: "Sci-fi/Action",
      director:"J.J. Abrams",
      starring:"Daisy Ridley, John Boyega, Adam Driver, Oscar Isaac, Carrie Fisher, Billy Dee Williams, Mark Hamill",
      description:"In the riveting conclusion of the landmark Skywalker saga, new legends will be born-and the final battle for freedom is yet to come.",
      trailer: "https://www.youtube.com/watch?v=8Qn_spdM5Zg",
      category: "StarWars" ,
    },
    {
      id:10,
      title: "Star Wars : The Mandalorian",
      detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/B0EBFC5E84A8CDCF197A7D2FCBDF5F56974AFC4DE313CEEF2C9A6B6231F9CC3E/scale?width=1440&aspectRatio=1.78&format=png",
      background:"https://wallpaperaccess.com/full/1726947.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/1C42324412D81E612EFD8E9DAB82B24EB43D057306A3F812214E9BA728DC0162/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: "2019 ‧ Space Western ‧ 3 Seasons ",
      plot:"It is the first live-action series in the Star Wars franchise, beginning five years after the events of Return of the Jedi (1983), and stars Pedro Pascal as the title character, a lone bounty hunter who goes on the run to protect the Force-sensitive child Grogu.      ",
      duration:"3 Seasons",
      releaseDate: "2019",
      genre: "Space Western",
      director:" Jon Favreau, Dave Filoni",
      starring:"Pedro Pascal, Gina Carano, Carl Weathers, Giancarlo Esposito, Rosario Dawson, Ming-na Wen",
      description:"The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
      trailer: "https://www.youtube.com/watch?v=aOC8E8z_ifw",
      category: "StarWars" ,
      recommended: true,
      original: true,
      series: true,
    },
    {
      id:11 ,
      title: "Star Wars : Obi - Wan Kenobi",
      detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/DF36C3E145545FC53827E7907B8E92577C94229ED06F8E9DEBB29D5ACAA9A7CE/scale?width=1440&aspectRatio=1.78&format=png",
      background:"https://techcrunch.com/wp-content/uploads/2022/05/oJ1KKAKiIuBA3s1tvtEa7NlQ2XM.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/9678FC74FB52573A4F9E8CFEB7E05C930094B1590C1175C530B014E14AA19434/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: "2022 ‧ Adventure ‧ 1 Season ",
      plot:"Set ten years after the events of Star Wars: Episode III - Revenge of the Sith (2005), the series follows Kenobi as he sets out to rescue the kidnapped Princess Leia (Vivien Lyra Blair) from the Galactic Empire, leading to a confrontation with his former apprentice, Darth Vader (Hayden Christensen).",
      duration:"1 Season",
      releaseDate: "2022",
      genre: " Adventure ",
      director:"Deborah Chow",
      starring:"Ewan McGregor, Hayden Christensen, Moses Ingram, Vivien Lyra Blair, Vect Nokru, Indira Varma ",
      description:"Jedi Master Obi-Wan Kenobi has to save young Leia after she is kidnapped, all the while being pursued by Imperial Inquisitors and his former Padawan, now known as Darth Vader.",
      trailer: "https://www.youtube.com/watch?v=TWTfhyvzTx0",
      category: "StarWars" ,
      original: true,
      series: true,
    },
    {
      id:12 ,
      title: "Star Wars: The Book of Boba Fett",
      detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/22725A60D6821C9D6A5D851B3ACDE7B9C0B09BBD9EDCCB5E6FFD0900214D9679/scale?width=1440&aspectRatio=1.78&format=png",
      background:"https://lumiere-a.akamaihd.net/v1/images/6154816e0b979e0001c347a6-image_f6373620.jpeg?region=0,0,1536,864",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/E77A344BADB816740F2D0863A555D596B249CFCEFF1F8AA85A4A19D2C09078DC/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: "2021 ‧ Action fiction ‧ 1 season",
      plot:`The Book of Boba Fett” aims to simultaneously tackle two timelines: one that catches us up with everything that happened to Boba since “Return of the Jedi” and one that continues his story following season two of “The Mandalorian.” In this later timeline, he assumes the throne of Mos Espa on the planet Tatooine, a role once held by ruthless crime lord Jabba the Hutt`,
      duration:"1 Season",
      releaseDate: "2021",
      genre: "Action Fiction",
      director:"John Favreau, Dave Filoni",
      starring:"Temuera Morrison, Ming-Na Wen, Pedro Pascal, Mark Hamill, Jennifer Beals, Sophie Thatcher",
      description:"Bounty hunter Boba Fett and mercenary Fennec Shand navigate the underworld when they return to Tatooine to claim Jabba the Hutt's old turf.",
      trailer: "https://www.youtube.com/watch?v=rOJ1cw6mohw",
      category: "StarWars" ,
      original: true,
      series: true,
    },
    {
        id:13 ,
        title:"Captain America: Civil War",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/93534E4AD7A683A9FE0E64C52F50EA00F618C479D9D406C80E1C4F515BF4FE3F/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://cdn.mos.cms.futurecdn.net/hjJmqHnszVarJMnKgoKdq5-1200-80.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/FABF318CE0142C2AC915C2D6F9EA63F5ED04F6C907E52D831A0F54476825A62F/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2016 ‧ Action Sci-Fi ‧ 2h 27m",
        plot:"Political pressure mounts to install a system of accountability when the actions of the Avengers lead to collateral damage. The new status quo deeply divides members of the team. Captain America (Chris Evans) believes superheroes should remain free to defend humanity without government interference. Iron Man (Robert Downey Jr.) sharply disagrees and supports oversight. As the debate escalates into an all-out feud, Black Widow (Scarlett Johansson) and Hawkeye (Jeremy Renner) must pick a side.",
        duration:"2h 27m",
        releaseDate: "2016",
        genre: "Action Sci-Fi",
        director:"Joe Russo",
        starring:"Chris Evans, Robert Downey Jr, Anthony Mackie, Sebastian Stan, Jeremy Renner, Scarlett Johansson, Elizabeth Olsen, Paul Rudd",
        description:"Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man.",
        trailer:"https://www.youtube.com/watch?v=dKrVegVI0Us",
        category: "Marvel" ,
    },
    {
        id:14 ,
        title:"Doctor Strange",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/C2AE604E7D9CE812E227DAF189010A0CD252ACF15CA68413AEEAA54BB396F0CE/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://www.hollywoodreporter.com/wp-content/uploads/2022/04/SSD1080_comp_v198.1074-H-2022.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/78BE4ABDBE00642AE6D6709FDD14AC6D7D816095752ECF13D3C9642AEA7B88C4/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2016 ‧ Action/Adventure ‧ 1h 55m",
        plot:"Dr. Stephen Strange's (Benedict Cumberbatch) life changes after a car accident robs him of the use of his hands. When traditional medicine fails him, he looks for healing, and hope, in a mysterious enclave. He quickly learns that the enclave is at the front line of a battle against unseen dark forces bent on destroying reality. Before long, Strange is forced to choose between his life of fortune and status or leave it all behind to defend the world as the most powerful sorcerer in existence.",
        duration:"1h 55m",
        releaseDate: "2016",
        genre: "Action/Adventure",
        director:"Scott Derrickson",
        starring:"Benedict Cumberbatch, Benedict Wong, Rachel McAdams",
        description:"While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
        trailer:"https://www.youtube.com/watch?v=Lt-U_t2pUHI",
        category: "Marvel" ,
        recommended: true,
    },
    {
        id:15 ,
        title:"Guardians of the Galaxy",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/9CDD9868380630ECE2D1F71A0B6E12A72C07838F45A80AD66E11D34D177278F0/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://images.thedirect.com/media/article_full/guardians-galaxy-mcu.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/F968B82BEA42F23007EB590619340EC332DFB3126AFC7FED7C3BFEB63AC5144A/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2014 ‧ Action Adventure Comedy ‧ 2h 1m",
        plot:"Brash space adventurer Peter Quill (Chris Pratt) finds himself the quarry of relentless bounty hunters after he steals an orb coveted by Ronan, a powerful villain. To evade Ronan, Quill is forced into an uneasy truce with four disparate misfits: gun-toting Rocket Raccoon, treelike-humanoid Groot, enigmatic Gamora, and vengeance-driven Drax the Destroyer. But when he discovers the orb's true power and the cosmic threat it poses, Quill must rally his ragtag group to save the universe.",
        duration:"2h 1m",
        releaseDate: "2014",
        genre: "Action Adventure Comedy",
        director:"James Gunn",
        starring:"Chris Pratt, Zoe Saldana, Vin Diesel, Sean Gunn, Dave Bautista",
        description:"A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
        trailer:"https://www.youtube.com/watch?v=d96cjJhvlMA",
        category: "Marvel" ,
    },
    {
        id:2 ,
        title:"Spider-Man: Homecoming",
        detailPhoto:"https://i0.wp.com/www.youthesource.com/wp-content/uploads/2018/09/Spiderman-Discussion-Guide.jpg?fit=760%2C430",
        background:"https://cdn.mos.cms.futurecdn.net/QXKcFLFHW8iXZQ9nsQDhd7-1200-80.jpg",
        image:"https://whatsondisneyplus.com/wp-content/uploads/2023/01/spiderman-homcoming.jpg",
        tags:"2017 ‧ Action Adventure Sci-Fi ‧ 2h 13m",
        plot:"Thrilled by his experience with the Avengers, young Peter Parker returns home to live with his Aunt May. Under the watchful eye of mentor Tony Stark, Parker starts to embrace his newfound identity as Spider-Man. He also tries to return to his normal daily routine -- distracted by thoughts of proving himself to be more than just a friendly neighborhood superhero. Peter must soon put his powers to the test when the evil Vulture emerges to threaten everything that he holds dear.",
        duration:"2h 13m",
        releaseDate: "2017",
        genre: "Action/Adventure",
        director:"Jon Watts",
        starring:"Tom Holland, Zendeya, Michael Keaton, Robert Downey Jr, Marisa Tomei, Laura Harrier",
        description:"Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.",
        trailer:"https://www.youtube.com/watch?v=rk-dF1lIbIg",
        category: "Marvel" ,
        
    },
    {
        id:17 ,
        title:"Black Panther",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/37F440CD37BF728065E14ABBF0DBC44413DA68FE273D8901D20577B78094AB8B/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://gh.cdn.sewest.net/assets/ident/pulse/59756537/TRM-Outfit-BlackPanther-MCUSoloMovie-1920x1080-TG-Final-5twmvcedw.jpg?quality=65",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/E9C4697F1745DEF68CD73B638BE6FCFB72B537788FB4F252E04B7BB745EE27A9/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2018 ‧ Action Adventure Sci-Fi ‧ 2h 14m",
        plot:"After the death of his father, T'Challa returns home to the African nation of Wakanda to take his rightful place as king. When a powerful enemy suddenly reappears, T'Challa's mettle as king -- and as Black Panther -- gets tested when he's drawn into a conflict that puts the fate of Wakanda and the entire world at risk. Faced with treachery and danger, the young king must rally his allies and release the full power of Black Panther to defeat his foes and secure the safety of his people.",
        duration:"2h 14m",
        releaseDate: "2018",
        genre: "Action Adventure Sci-Fi",
        director:"Ryan Coogler",
        starring:"Chadwick Boseman, Lupita Nyong'o, Letitia Wright, Michael B Jordan, Danai Gurira, Winston Duke",
        description:"T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
        trailer:"https://www.youtube.com/watch?v=xjDjIWPwcPU",
        category: "Marvel" ,
    },
    {
        id:18 ,
        title:"Avengers: Infinity War",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/1832D5CDF72E88186376612AB6176395CD8E0C6D9A3937F00D5C238C2AFB10ED/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/6E9A372F451B9BFE61D81FF9089214CA4F1F57CEF305E55D40E77D1E636C4F91/scale?width=2880&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/B07FABAA52E9F1962D1A3EE997F99564D8F77C567258EA93C17485A646776504/scale?width=400&aspectRatio=1.78&format=jpeg",
        tags:"2018 ‧ Action Adventure Sci-Fi ‧ 2h 29m",
        plot:"Iron Man, Thor, the Hulk and the rest of the Avengers unite to battle their most powerful enemy yet -- the evil Thanos. On a mission to collect all six Infinity Stones, Thanos plans to use the artifacts to inflict his twisted will on reality. The fate of the planet and existence itself has never been more uncertain as everything the Avengers have fought for has led up to this moment.",
        duration:"2h 29m",
        releaseDate: "2018",
        genre: " Action Adventure Sci-Fi",
        director:"Anthony Russo, Joe Russo",
        starring:"Robert Downey Jr, Josh Brolin, Chris Hemsworth, Scarlett Johansson, Chris Evans, Tom Holland, Mark Ruffalo ",
        description:"The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
        trailer:"https://www.youtube.com/watch?v=6ZfuNTqbHE8",
        category: "Marvel" ,
        recommended: true,
    },
    {
        id:19 ,
        title:"Spider-Man: No Way Home",
        detailPhoto:"https://whatsondisneyplus.com/wp-content/uploads/2022/04/spiderman-no-way-home.jpg",
        background:"https://i.ytimg.com/vi/0aIR2oe6h-Y/maxresdefault.jpg",
        image:"https://commentaryboxsports.com/wp-content/uploads/2022/03/Is-Spider-Man-No-Way-Home-Coming-to-Disney-Plus.jpg",
        tags:"2021 ‧ Action Adventure ‧ 2h 28m",
        plot:"Spider-Man: No Way Home is a 2021 American superhero film based on the Marvel Comics character Spider-Man, co-produced by Columbia Pictures and Marvel Studios and distributed by Sony Pictures Releasing. It is the sequel to Spider-Man: Homecoming (2017) and Spider-Man: Far From Home (2019), and the 27th film in the Marvel Cinematic Universe (MCU). The film was directed by Jon Watts and written by Chris McKenna and Erik Sommers. It stars Tom Holland as Peter Parker / Spider-Man alongside Zendaya, Benedict Cumberbatch, Jacob Batalon, Jon Favreau, Jamie Foxx, Willem Dafoe, Alfred Molina, Benedict Wong, Tony Revolori, Marisa Tomei, Andrew Garfield, and Tobey Maguire. In the film, Parker asks Dr. Stephen Strange (Cumberbatch) to use magic to make his identity as Spider-Man a secret again following its public revelation at the end of Far From Home. When the spell goes wrong because of Parker's actions, the multiverse is broken open, which allows visitors from alternate realities to enter Parker's universe.",
        duration:"2h 28m",
        releaseDate: "2021",
        genre: "Action Adventure",
        director:"Jon Watts",
        starring:"Tom Holland, Zendeya, Tobey Maguire, Andrew Garfield, Marisa Tomei, Willem Dafoe",
        description:"With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
        trailer:"https://www.youtube.com/watch?v=JfVOs4VSpmA",
        category: "Marvel" ,
        
    },
    {
        id:7 ,
        title:"Avengers: Endgame",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/76EAD3FE7834164B73EF7440C8D416BCDA876F0BF736E5AA45ACC1B6C743A1FF/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://images.hdqwalls.com/wallpapers/disney-plus-avengers-endgame-4k-jv.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/863E75A035911DBA10F8D7EE1E433A12A1BF4915670B66597AC31C585A291942/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2019 ‧ Action Adventure Drama ‧ 3h 1m",
        plot:"Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.",
        duration:"3h 1m",
        releaseDate: "2019",
        genre: "Action Adventure Drama",
        director:"Anthony Russo, Joe Russo",
        starring:"Robert Downey Jr, Chris Evans, Scarlett Johansson, Chris Hemsworth, Mark Ruffalo, Jeremy Renner",
        description:"After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
        trailer:"https://www.youtube.com/watch?v=TcMBFSGVi1c",
        category: "Marvel" ,
        recommended: true,
    },
    {
        id:21 ,
        title:"Frozen",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/5709B8BECDF79C45171AFF60EDDD6A57314028E7F32FD9CA2B58832237FE1D52/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://4kwallpapers.com/images/wallpapers/frozen-elsa-disney-princess-animation-4480x2520-5072.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/5A04BBDD5CFD81AAD009775FE215D3DD8EE604E161603EF230644143815F2A81/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2013 ‧ Animation Adventure Comedy 1h 42m",
        plot:"When their kingdom becomes trapped in perpetual winter, fearless Anna (Kristen Bell) joins forces with mountaineer Kristoff (Jonathan Groff) and his reindeer sidekick to find Anna's sister, Snow Queen Elsa (Idina Menzel), and break her icy spell. Although their epic journey leads them to encounters with mystical trolls, a comedic snowman (Josh Gad), harsh conditions, and magic at every turn, Anna and Kristoff bravely push onward in a race to save their kingdom from winter's cold grip.",
        duration:"1h 42m",
        releaseDate:"2013",
        genre: "Animation Adventure Comedy",
        director:"Chris Buck, Jennifer Lee",
        starring:"Idina Menzel, Kristen Bell, Josh Gad, Jonathan Groff, Jennifer Lee",
        description:"When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.",
        trailer:"https://www.youtube.com/watch?v=TbQm5doF_Uc",
        category: "Disney" ,
        original: true,
        recommended: true,
    },
    {
        id:22 ,
        title:"The Lion King",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/E056317A4845B22EFFC0F553995629A4BBEBD036D745468D2283F8E15C46145F/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://i.pinimg.com/originals/b4/2b/5e/b42b5eb21099ccfbe4af5076f0e40a85.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/0C33CB391625A18FB4A6E08B51231F96062793E521D0AAB42067789B01F39280/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"1994 ‧ Animation Adventure Drama ‧ 1h 28m",
        plot:"This Disney animated feature follows the adventures of the young lion Simba (Jonathan Taylor Thomas), the heir of his father, Mufasa (James Earl Jones). Simba's wicked uncle, Scar (Jeremy Irons), plots to usurp Mufasa's throne by luring father and son into a stampede of wildebeests. But Simba escapes, and only Mufasa is killed. Simba returns as an adult (Matthew Broderick) to take back his homeland from Scar with the help of his friends Timon (Nathan Lane) and Pumbaa (Ernie Sabella).",
        duration:"1h 28m",
        releaseDate: "1994",
        genre: "Animation Adventure Drama",
        director:"Rob Minkoff, Roger Allers",
        starring:"Jeremy Irons, James Earl Jones, Matthew Broderick, Rowan Atkinson, Robbert Guillaume, Ernie Sabella, Jonathan Taylor Thomas, Nathan Lane ",
        description:"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
        trailer:"https://www.youtube.com/watch?v=lFzVJEksoDY",
        category: "Disney" ,
        original: true,
    },
    {
        id:23 ,
        title:"Dinosaur",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/DDA0E6486801290A2934D7C89B26087FBA7944497EA95C44DBC165828F0FA5E3/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://allears.net/wp-content/uploads/2020/04/disney-plus-dinosaur.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/2DA33A636D572B67D43F53D38600382061E5EF334597BD843E22E6157A03AB6F/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2000 ‧ Adventure/Family ‧ 1h 22m",
        plot:`This is the story of Aladar (Alfre Woodard), an iguanodon dinosaur raised by a family of lemurs. Their world is turned upside-down however, when meteors strike, turning their green world into a desert wasteland. Teaming up with a herd of other herbivores, the trek is on to find the "Nesting Ground" where water and vegetation is bountiful... but with carnivores behind them and nothing but desert around for miles, it doesn't look promising!`,
        duration:"1h 22m",
        releaseDate: "2000",
        genre: "Adventure/Family",
        director:"Eric Leighton",
        starring:"Alfre Woodard, D. B. Sweeney, Joan Plowright, Della Reese, Zachary Bostrom, Matt Adler, Cathy Cavadini",
        description:"An orphaned dinosaur raised by lemurs joins an arduous trek to a sanctuary after a meteorite shower destroys his family home.",
        trailer:"https://www.youtube.com/watch?v=vZnBR4SDIEs",
        category: "Disney" ,
        original: true,
    },
    {
        id:24 ,
        title:"Mulan",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/6F8E62B415250E641AB60BCA056EBF92EAAE551A10AF524857A3D33276E405C7/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://images.immediate.co.uk/production/volatile/sites/3/2019/05/MLAN2_mu2_sg56p_L-08969e4.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/D100BB6C7CB31A1C80CD1D023BC5827FA539DCA9AC1099B82788CEBE4965C0E6/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"1998 ‧ Animation Adventure Comedy ‧ 1h 27m",
        plot:"Fearful that her ailing father will be drafted into the Chinese military, Mulan (Ming-Na Wen) takes his spot -- though, as a girl living under a patriarchal regime, she is technically unqualified to serve. She cleverly impersonates a man and goes off to train with fellow recruits. Accompanied by her dragon, Mushu (Eddie Murphy), she uses her smarts to help ward off a Hun invasion, falling in love with a dashing captain along the way.",
        duration:"1h 27m",
        releaseDate: "1998",
        genre: "Animation Adventure Comedy",
        director:"Niki Caro",
        starring:"Ming-Na Wen, Ming-Na Wen ",
        description:"To save her father from death in the army, a young maiden secretly goes in his place and becomes one of China's greatest heroines in the process.",
        trailer:"https://www.youtube.com/watch?v=HKH7_n425Ss",
        category: "Disney" ,
        original: true,
    },
    {
        id:25 ,
        title:"Lilo & Stitch",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/785341BB797F24BEB4BBE78C763939567295AB4BA26894200795F0F5072A9E8E/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://hips.hearstapps.com/digitalspyuk.cdnds.net/17/04/1485279080-lilo-and-stitch.jpg",
        image:"https://static1.srcdn.com/wordpress/wp-content/uploads/2020/03/Lilo-and-Stitch-Disney-changes.jpg",
        tags:"2002 ‧ Family/Comedy ‧ 1h 25m",
        plot:`A tale of a young girl's close encounter with the galaxy's most wanted extraterrestrial. Lilo is a lonely Hawaiian girl who adopts a small ugly "dog," whom she names Stitch. Stitch would be the perfect pet if he weren't in reality a genetic experiment who has escaped from an alien planet and crash-landed on Earth. Through her love, faith and unwavering belief in ohana, the Hawaiian concept of family, Lilo helps unlock Stitch's heart and gives him the ability to care for someone else.`,
        duration:"1h 25m",
        releaseDate: "2002",
        genre: "Family/Comedy",
        director:"Chris Sanders, Dean DeBlois",
        starring:"Chris Sanders, Daveigh Chase, Ving Rhames, Tia Carrere, Kevin McDonald",
        description:"A young and parentless girl adopts a 'dog' from the local pound, completely unaware that it's supposedly a dangerous scientific experiment that's taken refuge on Earth and is now hiding from its creator and those who see it as a menace.",
        trailer:"https://www.youtube.com/watch?v=9OAC55UWAQs",
        category: "Disney" ,
        original: true,
    },
    {
        id:26 ,
        title:"Beauty and the Beast",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/38883F8637B2B2A632F17A73F49DAE6468F72650F3292C5FB9F8166810CCD7EB/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://rare-gallery.com/mocahbig/72755-Beauty-And-The-Beast-1991-HD-Wallpaper.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/54FDB59A9E6E553E5A62E6B9A09028F18AF39AB2900505E1CE15CAF746DCAD0E/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"1991 ‧ Musical/Fantasy ‧ 1h 24m",
        plot:"Follow the adventures of Belle, a bright young woman who finds herself in the castle of a prince who's been turned into a mysterious beast. With the help of the castle's enchanted staff, Belle soon learns the most important lesson of all -- that true beauty comes from within.",
        duration:"1h 24m",
        releaseDate: "1991",
        genre: "Musical/Fantasy",
        director:"Gary Trousdale, Kirk Wise",
        starring:"Paige O'Hara, Robby Benson, Angela Lansbury, Jerry Orbach, David Ogden Stiers",
        description:"A prince cursed to spend his days as a hideous monster sets out to regain his humanity by earning a young woman's love.",
        trailer:"https://www.youtube.com/watch?v=iurbZwxKFUE",
        category: "Disney" ,
        original: true,
    },
    {
        id:27 ,
        title:"Tarzan",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/5F123A950B56C865D1BCF741D9AA59940BA4BC97B94781300B856119344A62F6/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://i0.wp.com/fullcirclecinema.com/wp-content/uploads/2020/05/tarzandisney3905.jpg?fit=1920%2C1080&ssl=1",
        image:"https://whatsondisneyplus.com/wp-content/uploads/2020/06/Tarzan.jpg",
        tags:"1999 ‧ Adventure/Romance ‧ 1h 28m",
        plot:"In this Disney animated tale, the orphaned Tarzan (Tony Goldwyn) grows up in the remote African wilderness, raised by the gentle gorilla Kala (Glenn Close). When a British expedition enters the jungle, Tarzan encounters the beautiful Jane (Minnie Driver) and recognizes that, like her, he's human. Falling in love with Jane, Tarzan is torn between embracing civilization and staying with his gorilla family, which becomes threatened by the ruthless hunter Clayton (Brian Blessed).",
        duration:"1h 28m",
        releaseDate:"1999",
        genre:"Adventure/Romance",
        director:"Kevin Lima, Chris Buck",
        starring:"Tony Goldwyn, Glenn Close, Minnie Driver, Brian Blessed",
        description:"A man raised by gorillas must decide where he really belongs when he discovers he is a human.",
        trailer:"https://www.youtube.com/watch?v=ie53R2HEZ6g",
        category: "Disney" ,
        original: true,
    },
    {
        id:28 ,
        title:"Aladdin",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/DFCB6FF825D250764CBF61DB55B9B646FCD23F9996A1A447DBBCAE3AA1B84DF0/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/025076C4F2358158C29D512914EB7CC5B8C3EC0371E8399509E7E8FDF07DB46E/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/5A74223BC7390B74F0A3AA140373C8CC49FCB54237FC7C459F943F06EDABC467/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"1992 ‧ Musical/Family ‧ 1h 30m",
        plot:"Aladdin is a lovable street urchin who meets Princess Jasmine, the beautiful daughter of the sultan of Agrabah. While visiting her exotic palace, Aladdin stumbles upon a magic oil lamp that unleashes a powerful, wisecracking, larger-than-life genie. As Aladdin and the genie start to become friends, they must soon embark on a dangerous mission to stop the evil sorcerer Jafar from overthrowing young Jasmine's kingdom.",
        duration:"1h 30m",
        releaseDate:"1992",
        genre: "Musical/Family",
        director:"Ron Clements, John Musker",
        starring:"Robin Williams, Scott Weinger, Linda Larkin",
        description:"A kindhearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.",
        trailer:"https://www.youtube.com/watch?v=eTjHiQKJUDY",
        category: "Disney" ,
        original: true,
    },
    {
        id:29 ,
        title:"Lightyear",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/F0305C1993FA02BAB78E73487E3DB1B5572EE3B98F4E53DE1D1914EE01DBEAC1/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://cdn.mos.cms.futurecdn.net/WanmQg9ctVZXewPa4zb7Nm.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/29859918D787A9A644D348B59AB90854C58DFD65DE68C50B9FBA28C423405167/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2022 ‧ Family/Sci-fi ‧ 1h 45m",
        plot:"Legendary space ranger Buzz Lightyear embarks on an intergalactic adventure alongside ambitious recruits Izzy, Mo, Darby, and his robot companion, Sox. As this motley crew tackles their toughest mission yet, they must learn to work together as a team to escape the evil Zurg and his dutiful robot army that are never far behind.",
        duration:"1h 45m",
        releaseDate: "2022",
        genre: "Family/Sci-fi",
        director:"Angus MacLane",
        starring:"Chris Evans, Taika Waititi, Keke Palmer",
        description:"While spending years attempting to return home, marooned Space Ranger Buzz Lightyear encounters an army of ruthless robots commanded by Zurg who are attempting to steal his fuel source.",
        trailer:"https://www.youtube.com/watch?v=BwZs3H_UN3k",
        category:"Pixar" ,
        original: true,
    },
    {
        id:30 ,
        title:"Toy Story 4",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/C1D591CF2EC02C43A0B174EC6B43DFE5725D42839ACE0B26A5737451DB399C0A/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://media-cldnry.s-nbcnews.com/image/upload/newscms/2019_25/2905636/190621-toy-story-4-ew-1138a.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/97773D3AD23DD9942EE4EDDB26E775D192E7AC6B038E459A6CF91D0107BB33AF/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2019 ‧ Family/Adventure ‧ 1h 40m",
        plot:"Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woody's slight detour leads him to his long-lost friend Bo Peep. As Woody and Bo discuss the old days, they soon start to realize that they're worlds apart when it comes to what they want from life as a toy.",
        duration:"1h 40m",
        releaseDate: "2019",
        genre: "Family/Adventure",
        director:"Josh Cooley",
        starring:"Tom Hanks, Tim Allen, Keanu Reeves, Annie Potts, Bonnie Hunt",
        description:`When a new toy called "Forky" joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.`,
        trailer:"https://www.youtube.com/watch?v=wmiIUN-7qhE",
        category:"Pixar" ,
        
    },
    {
        id:31 ,
        title:"Incredibles 2",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/DFF5CF229AEA4CA7F0F2129E2524565F350FE90C1BB63116C7FF0EA8DC9A120D/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/DFF5CF229AEA4CA7F0F2129E2524565F350FE90C1BB63116C7FF0EA8DC9A120D/scale?width=1440&aspectRatio=1.78&format=png",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/FE13ED0824D296424A0DFF86383F034D7D6C0A98365B13ED06DD7B978B25E6B3/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2018 ‧ Family/Adventure ‧ 2h 6m",
        plot:"Telecommunications guru Winston Deavor enlists Elastigirl to fight crime and make the public fall in love with superheroes once again. That leaves Mr. Incredible with one of his greatest challenges ever -- staying home and taking care of three rambunctious children. As Violet, Dash and Jack-Jack offer him a new set of headaches, a cybercriminal named Screenslaver launches his dastardly plan -- hypnotizing the world through computer screens.",
        duration:"2h 6m",
        releaseDate: "2018",
        genre: "Family/Adventure",
        director:"Brad Bird",
        starring:"Brad Bird, Holly Hunter, Craig T. Nelson, Bob Odenkirk",
        description:"The Incredibles family takes on a new mission which involves a change in family roles: Bob Parr (Mr. Incredible) must manage the house while his wife Helen (Elastigirl) goes out to save the world.",
        trailer:"https://www.youtube.com/watch?v=i5qOzqD9Rms",
        category:"Pixar" ,
    },
    {
        id:32 ,
        title:"Monsters, Inc.",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/3C54FA1632B2433801BB4591552EAA66996E53643BDA5DDDABD801285044360C/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://cdn.vox-cdn.com/thumbor/4Xz-znF2w-mucKPF5L1WSycHE48=/1400x788/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/16019170/Mike_Sulley_Boo_monsters_inc.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/AFB43D8062ABDB29DF18E323CF803AAA33BCCF5F754B12CEEBDAC881DE72155E/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2001 ‧ Animation Adventure Comedy ‧ 1h 32m",
        plot:"Monsters Incorporated is the largest scare factory in the monster world, and James P. Sullivan (John Goodman) is one of its top scarers. Sullivan is a huge, intimidating monster with blue fur, large purple spots and horns. His scare assistant, best friend and roommate is Mike Wazowski (Billy Crystal), a green, opinionated, feisty little one-eyed monster. Visiting from the human world is Boo (Mary Gibbs), a tiny girl who goes where no human has ever gone before.",
        duration:"1h 32",
        releaseDate: "2001",
        genre: "Animation Adventure Comedy",
        director:"Pete Docter",
        starring:"Billy Crystal, John Goodman, Pete Docter, Mary Gibbs, Bob Peterson, Bonnie Hunt",
        description:"In order to power the city, monsters have to scare children so that they scream. However, the children are toxic to the monsters, and after a child gets through, two monsters realize things may not be what they think.",
        trailer:"https://www.youtube.com/watch?v=CGbgaHoapFM",
        category:"Pixar" ,
    },
    {
        id:33 ,
        title:"Brave",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/4625BCC2E513A91AA0EDB7D12F090E13E7F3DECCDF964414A6F32759893F0701/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://www.intofilm.org/intofilm-production/1341/scaledcropped/3000x1688/resources/1341/brave-ep-disney.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/8C1BA16AED00C6E7B67B688E1146CA245698169FE4FDB0B3E0CCF4273E83B47E/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2012 ‧ Animation Adventure Comedy ‧ 1h 33m",
        plot:`Merida (Kelly Macdonald), the impetuous but courageous daughter of Scottish King Fergus (Billy Connolly) and Queen Elinor (Emma Thompson), is a skilled archer who wants to carve out her own path in life. Her defiance of an age-old tradition angers the Highland lords and leads to chaos in the kingdom. Merida seeks help from an eccentric witch (Julie Walters), who grants her an ill-fated wish. Now, Merida must discover the true meaning of courage and undo a beastly curse before it's too late.`,
        duration:"1h 33m",
        releaseDate: "2012",
        genre: "Animation Adventure Comedy",
        director:"Brenda Chapman, Mark Andrews",
        starring:"Kelly Macdonald, Robbie Coltrane, Emma Thompson, Julie Walters, Billy Connoly",
        description:"Determined to make her own path in life, Princess Merida defies a custom that brings chaos to her kingdom. Granted one wish, Merida must rely on her bravery and her archery skills to undo a beastly curse.",
        trailer:"https://www.youtube.com/watch?v=5fPmKfcaaWk",
        category:"Pixar" ,
    },
    {
        id:34 ,
        title:"WALL-E",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/23A68A3D04A775FF2CAE5177BA1BCB590C458CDB27DE0DF860F9685191857509/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://wallpaperaccess.com/full/1291994.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/5669753D6F71EB5668B6854BC1EB36BA99217B3EC1D4211EC37A894B6F654AD6/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2008 ‧ Animation Adventure Family ‧ 1h 37m",
        plot:"WALL-E, short for Waste Allocation Load Lifter Earth-class, is the last robot left on Earth. He spends his days tidying up the planet, one piece of garbage at a time. But during 700 years, WALL-E has developed a personality, and he's more than a little lonely. Then he spots EVE (Elissa Knight), a sleek and shapely probe sent back to Earth on a scanning mission. Smitten WALL-E embarks on his greatest adventure yet when he follows EVE across the galaxy.",
        duration:"1h 37m",
        releaseDate: "2008",
        genre: "Animation Adventure",
        director:"Andrew Stanton",
        starring:"Ben Burtt, Elissa Knight, Andrew Saxton,",
        description:"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
        trailer:"https://www.youtube.com/watch?v=CZ1CATNbXg0",
        category:"Pixar" ,
        recommended: true,
    },
    {
        id:35 ,
        title:"Ratatouille",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/FDAADE52204072766EABD902077798A5B6E0A05EC654A45314DA7B4B18255E09/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://variety.com/wp-content/uploads/2007/06/rexfeatures_1622528a.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/69F9436F08D1FA3FAD59F13B1AA8A7D0C7BABB2CF2FC227741FDBF6387D76F10/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2007 ‧ Animation Adventure Comedy ‧ 1h 51m",
        plot:"Remy dreams of becoming a great chef, despite being a rat in a definitely rodent-phobic profession. He moves to Paris to follow his dream, and with the help of hapless garbage boy Linguini he puts his culinary skills to the test in the kitchen but he has to stay in hiding at the same time, with hilarious consequences. Remy eventually gets the chance to prove his culinary abilities to a great food critic but is the food good? A Pixar animation.",
        duration:"1h 51m",
        releaseDate: "2007",
        genre: "Animation Adventure Comedy",
        director:"Brad Bird",
        starring:"Patton Oswalt, Will Arnett, Lou Romano",
        description:"A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.",
        trailer:"https://www.youtube.com/watch?v=NgsQ8mVkN8w",
        category:"Pixar" ,
    },
    {
        id:36 ,
        title:"Finding Nemo",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/284C2890A258F7547012BC16EF08DA9E3909C85AE66CDB0924B7273E112AF821/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/finding-nemo-theory-1623752052.jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/A6B8580D6192BB96B408A8CFFC1A338B933FBC446A10B56349DE7F9CB51C4EDE/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2003 ‧ Animation Adventure Comedy ‧ 1h 40m",
        plot:"Marlin (Albert Brooks), a clown fish, is overly cautious with his son, Nemo (Alexander Gould), who has a foreshortened fin. When Nemo swims too close to the surface to prove himself, he is caught by a diver, and horrified Marlin must set out to find him. A blue reef fish named Dory (Ellen DeGeneres) -- who has a really short memory -- joins Marlin and complicates the encounters with sharks, jellyfish, and a host of ocean dangers. Meanwhile, Nemo plots his escape from a dentist's fish tank.",
        duration:"1h 40m",
        releaseDate: "2003",
        genre: "Animation Adventure Comedy",
        director:"Andrew Stanton",
        starring:"Alexander Gould, Albert Brooks, Ellen DeGeneres, Willem Dafore, Allison Janney",
        description:"After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
        trailer:"https://www.youtube.com/watch?v=9oQ628Seb9w&t=2s",
        category:"Pixar",
    },
    {
        id:37 ,
        title:"Man vs Puma",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/291F68B03C54FA684F3496CA83CD7847222C806914359B9D69F1DAE61BE6A2A7/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/87AA94F4BF88272C697F40C56626E44592DEDC26DEDF9F689FA0C60D6A6F3C15/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/47DCBEDC24DC7A15A97A0F27B0805E8F88F1B79F1613890FA096B60103632B1D/scale?width=400&aspectRatio=1.78&format=jpeg",
        tags:" 2018 ‧ Documentary Animals & Nature ‧ 43m ",
        plot:"Big cat expert Boone Smith travels to Patagonia to observe pumas thriving in the wild under increased conservation efforts; the cats have not learned to fear humans, making this the one place where people can observe their behavior up close",
        duration:"43m",
        releaseDate: "2018",
        genre: "Documentary Animals & Nature",
        director:"Alex Sletten",
        starring:"Boone Smith",
        description:"Big cat expert Boone Smith travels to Patagonia to observe pumas thriving in the wild under increased conservation efforts; the cats have not learned to fear humans, making this the one place where people can observe their behavior up close.",
        trailer:"https://www.youtube.com/watch?v=oc8vpx_ARRQ&t=14s",
        category:"NationalGeo" ,
    },
    {
        id:38 ,
        title:"Ocean's Weirdest",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/DD1C71FFE651982D47ADB9823E53D8B776E5D74BB9EFB682CA260EA4751660B4/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/F5CC3480D72770B505BA993F5A101127E4AAADC29CEE544B0C2309F9EB5268A1/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/5FD7F7902D1F7697B5F7BFBA3AF0F5A896EF18BC86AE7BD1778C667D6CA5AD66/scale?width=400&aspectRatio=1.78&format=jpeg",
        tags:"2022 ‧ Docuseries Animals & Nature ‧ 1 Season ",
        plot:"Beneath the waves there are weird and freaky creatures locked in a struggle to outwit, outswim and outlast each other. Discover the wild world that lives under the sea on Ocean's Weirdest.",
        duration:"1 Season",
        releaseDate: "2022",
        genre: "Docuseries Animals & Nature",
        director:"David Hay, Wendy Tetley",
        starring:"David Carling",
        description:"The filmmaker delves into the distinct behavioural patterns exhibited by ocean creatures during their attempts to survive, mate and adapt to their surroundings.",
        trailer:"https://www.youtube.com/watch?v=8PDj22hFow8",
        category:"NationalGeo" ,
        series: true,
    },
    {
        id:39 ,
        title:"Limitless with Chris Hemsworth",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/DB8C9A3FD24FF8EF85E16AB75C17BC357AE75EC02263011AF4B829FCEF2E809B/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/C77C92E99CDF98F1BE4BD8BE48ADF9AFA2639AA3AA925E7896C457147139E576/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/B99E52F5905E1F40B27458CCDC0D3608AA83D92DF917795BCA1C49EB5E939091/badging?width=400&aspectRatio=1.78&format=jpeg&label=disneyplusoriginal",
        tags:" 2022 ‧ Docuseries, Lifestyle, Action-Adventure ‧ 1 Season ",
        plot:"A different way we can live better for longer: regenerating damage, maximizing strength, building resilience, shocking the body, supercharging memory and confronting mortality.",
        duration:"1 Season",
        releaseDate: "2022",
        genre: "Docuseries, Lifestyle, Action-Adventure",
        director:"Darren Aronofsky, Ari Handel",
        starring:"Chris Hemsworth, Peter Attia Elsa Pataky",
        description:"Chris Hemsworth explores the different ways humans can live better for longer by taking on physical challenges such as diving in ice or climbing skyscrapers.",
        trailer:"https://www.youtube.com/watch?v=4AxfL9Y4boE",
        category:"NationalGeo" ,
        series: true,
    },
    {
        id:40 ,
        title:"The Flagmakers",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/6225588D3D22F516102319E9B3A0FCA580D4289D9103D8954B06963C01237CA6/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/A9A6D8D4224161EA27DDF6EA44E971E29E0BEC8AF075AC8C5D90A9D159F4AE5A/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/6EF900C92ABC5D61EBDAD274E9C6923AA0FFFCA02A31DC8BC732DEC09712236E/badging?width=400&aspectRatio=1.78&format=jpeg&label=disneyplusoriginal",
        tags:"2022 ‧ Documentary ‧ 35m ",
        plot:`From National Geographic Documentary Films, Academy Award-winning director Cynthia Wade, award-winning director Sharon Liese and executive producer Giannis Antetokounmpo, "The Flagmakers" poses one of today's most pressing questions: who is the American flag for? Employee-owned Eder Flag in Oak Creek, Wisconsin, sews and ships five million American flags a year. The flagmakers - locals, immigrants and refugees - stitch stars and stripes as they wrestle with identity and belonging.`,
        duration:"35m",
        releaseDate: "2022",
        genre: " Documentary",
        director:"Sharon Liese, Cynthia Wade",
        starring:"The Flagmakers",
        description:"a meditation on the American dream, follows workers at the country’s largest manufacturer of American flags and flagpoles, including the refugees and immigrants who have risked everything to come to the USA.",
        trailer:"https://www.youtube.com/watch?v=QKCN_ppi2yw",
        category:"NationalGeo" ,
    },
    {
        id:41 ,
        title:"Victoria Falls Africa's Garden of Eden",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/5A526B8A26D8FD2236D098F8390444C063BF2D337A53A25AAD2F30AEAD108E3E/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/0D0B1B56771EBB9AE68BC2296496CBECA20901B34A47A34AD9685DE50A596E70/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/A9EB68517A07D3CDF22CAF1F3B39ADE466280CDFE7A5BF2F1C9308809EF2CDC1/scale?width=400&aspectRatio=1.78&format=jpeg",
        tags:"2020 ‧ Documentary, Animals & Nature ‧ 44m ",
        plot:"One can see them from distances up to 30km: Like a mumbling, bubbling volcano, ready to erupt, a glowing cloud rises from the earth",
        duration:"44m",
        releaseDate: "2020",
        genre: "Documentary, Animals & Nature",
        director:"Thomas Behrend",
        starring:"Constantin von Westphalen",
        description:"One can see them from distances up to 30km: Like a mumbling, bubbling volcano, ready to erupt, a glowing cloud rises from the earth.",
        trailer:"https://www.youtube.com/watch?v=gdtfjm1peDc",
        category:"NationalGeo" ,
    },
    {
        id:42 ,
        title:"Super/Natural",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/24765C14F913D00AB3C0CB5B8F3853F4F0E1A7FAE2DB52B34C10F71CEB24DD4C/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/E1994F4FE352A821CCCB5BC58A99C7C0597ABBEBE3B5CC17A756E5BC2D582F50/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/7F7FB344FE9EEE6780F30625CDE0F5FADA4562D3C0F9D4B6545378232BE5D1B4/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2022 ‧ Docuseries, Animals & Nature ‧ 1 Season  ",
        plot:"Using the latest scientific innovations and filmmaking technology, the powers and super-senses of the world's animals will be revealed, inviting viewers to experience the natural world as a specific species does.",
        duration:"1 Season",
        releaseDate: "2022",
        genre: "Docuseries, Animals & Nature",
        director:"National Geographic",
        starring:"Benedict Cumberbatch",
        description:"Witness the secret powers of extraordinary animals, experience the world as they do and see the SUPER/NATURAL side of nature as never before. This title is executive produced by James Cameron and narrated by Benedict Cumberbatch",
        trailer:"https://www.youtube.com/watch?v=GDYEVR12aoE",
        category:"NationalGeo" ,
        series: true,
    },
    {
        id:43 ,
        title:"Welcome to Earth",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/93E8F77E9BE98A7F3FA783EE0D260D6579BE23703D0CF0F9473B0A13C6AF2A0D/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/8C7DB3DB50EE3CBF59C7098B533DF09BA881D85EF4E4CDCD72F525D9B765C3FD/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://i.ytimg.com/vi/WUHbPgbFq14/maxresdefault.jpg ",
        tags:"2021 ‧ Family, Docuseries, Animals & Nature ‧ 1 Season ",
        plot:"Will Smith travels to the extreme ends of the earth from active volcanoes to deep ocean adventures.",
        duration:"1 Season",
        releaseDate: "2021",
        genre: "Family, Docuseries, Animals & Nature",
        director:"National Geographic",
        starring:"Will Smith, Diva Amon, Cory Richards",
        description:"The Disney+ orignal series from National Geographic follows Will Smith on an extraordinary adventure around the world to explore Earth's greatest wonders and reveal its most hidden secrets. Throughout the six-part limited series produced by filmmaker Darren Aronofsky, Protozoa Pictures, Jane Root's Nutopia and Westbrook Stuidios, Will is guided by elite explorers on an awe-inspiring journey",
        trailer:"https://www.youtube.com/watch?v=i0MTCXgil1M",
        category:"NationalGeo",
        series: true,
    },
    {
        id:44 ,
        title:"America The Beautiful",
        detailPhoto:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/8F80C316D8B0F4A84C679BD3B5052AA0FFBF6C1C4BDC1894D4056DD677D6DBBE/scale?width=1440&aspectRatio=1.78&format=png",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/22CEA5694B661AB902F0A18C7F407F99874FE437E481220A4C9AB05977160BB5/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/70E7D8FF6400585D0D0A95698CD99CEB7B800C32C162D2E123D5706B96888201/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2022 ‧ Docuseries, Animals & Nature ‧ 1 Season  ",
        plot:"It's the land we love and the land we think we know. We see America's breathtaking landscapes and wildlife as timeless, but the truth is very different. Its unique geography drives the forces of nature to extremes, shaping and reshaping the land and throwing down new challenges for life.",
        duration:"1 Season",
        releaseDate: "2022",
        genre: "Docuseries, Animals & Nature",
        director:"National Geographic",
        starring:"Michael B. Jordan",
        description:"North America and its wildlife as you've never seen them before - heroic animals, new animal behavior and breath-taking landscape visuals",
        trailer:"https://www.youtube.com/watch?v=p8jYJQzcKpY",
        category:"NationalGeo",
        series: true,
    }
    
    
  ];