export const films = [
    {
      id: 1,
      title: "Star Wars: Episode I - The Phantom Menace",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/C738C29A957035D7109132F2864962B10E32314C74517C591AA99BA4189C3EFD/scale?width=1200&aspectRatio=1.78&format=jpeg",
      background:"https://c4.wallpaperflare.com/wallpaper/645/548/896/jedi-movies-sith-star-wars-wallpaper-preview.jpg",
      tags: "1999 - Sci-fi/Action 2h 16m ",
      description:"Two Jedi escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force, but the long dormant Sith resurface to claim their original glory.",
      trailer: "https://www.youtube.com/watch?v=bD7bpG-zDJQ&t=2s",
      categorgy: "StarWars" ,
      recommended: true,
      
    },
    {
      id: 16 ,
      title: "Star Wars: Episode II - Attack of the Clones",
      background:"https://images.squarespace-cdn.com/content/v1/5fbc4a62c2150e62cfcb09aa/1613622106884-P7HZ6NRBS1KT5ABGL7J9/AOTC.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/EA545D0F238ADD340517DBE4344899EC16F73C60D5DD8FE20C9B1D2D19AF6392/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: " 2002 ‧ Sci-fi/Action ‧ 2h 22m ",
      description:"Ten years after initially meeting, Anakin Skywalker shares a forbidden romance with Padmé Amidala, while Obi-Wan Kenobi investigates an assassination attempt on the senator and discovers a secret clone army crafted for the Jedi",
      trailer: "https://www.youtube.com/watch?v=gYbW1F_c9eM",
      categorgy: "StarWars" ,
    },
    {
      id:3 ,
      title: "Star Wars: Episode III - Revenge of the Sith",
      background:"https://rare-gallery.com/uploads/posts/549139-star-wars-star.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/8E45ABC57042AF80094DA193EA2FE089173703BBFBB853C490A1422324788D62/scale?width=1200&aspectRatio=1.78&format=jpeg ",
      tags: "2005 ‧ Action/Sci-fi ‧ 2h 20m ",
      description:"Three years into the Clone Wars, the Jedi rescue Palpatine from Count Dooku. As Obi-Wan pursues a new threat, Anakin acts as a double agent between the Jedi Council and Palpatine and is lured into a sinister plan to rule the galaxy.",
      trailer: "https://www.youtube.com/watch?v=5UnjrG_N8hU",
      categorgy: "StarWars" ,
      recommended: true,
    },
    {
      id:4 ,
      title: "Star Wars: Episode IV - A New Hope",
      background:"https://images6.alphacoders.com/613/thumb-1920-613328.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/78A138B561F468B457EEA22AB20C3C30772D1070DA64575B95C5B27B1EB9E17B/scale?width=800&aspectRatio=1.78&format=jpeg ",
      tags: " 1977 ‧ Sci-fi/Sci-fi ‧ 2h 1m ",
      description:"Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
      trailer: "https://www.youtube.com/watch?v=vZ734NWnAHA",
      categorgy: "StarWars" ,
    },
    {
      id:5 ,
      title: "Star Wars: Episode V - The Empire Strikes Back",
      background:"https://rare-gallery.com/mocahbig/77814-Star-WarsStar-Wars-Episode-V-The-Empire-Strikes-Back.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/9B5F5B3695F760B39713902E6C1D27893F5C45AA66B424516F8342515468536B/scale?width=800&aspectRatio=1.78&format=jpeg",
      tags: " 1980 ‧ Sci-fi/Adventure ‧ 2h 4m",
      description:"After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.",
      trailer: "https://www.youtube.com/watch?v=JNwNXF9Y6kY",
      categorgy: "StarWars" ,
      recommended: true,
    },
    {
      id:6 ,
      title: "Star Wars: Episode VI - Return of the Jedi",
      background:"https://img3.goodfon.com/wallpaper/nbig/f/92/star-wars-episode-vi---return.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/C6D2C704254F71B2DF415A48F653F769FF10900D05C3146A6E5CFF5C6BDA1AF1/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: " 1983 ‧ Sci-fi/Action ‧ 2h 11m ",
      description:"After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star. Meanwhile, Luke struggles to help Darth Vader back from the dark side without falling into the Emperor's trap.",
      trailer: "https://www.youtube.com/watch?v=XgB4gaY2dWE",
      categorgy: "StarWars" ,
    },
    {
      id:20 ,
      title: "Star Wars: Episode VII - The Force Awakens",
      background:"https://whatsondisneyplus.com/wp-content/uploads/2019/10/force-awakens-e1570528179432.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/CF05493C681BE56C7D085E1131EE47D12D9BC505411E1D77BB2164D84AE0CC48/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: "2015 ‧ Sci-fi/Action ‧ 2h 16m",
      description:"As a new threat to the galaxy rises, Rey, a desert scavenger, and Finn, an ex-stormtrooper, must join Han Solo and Chewbacca to search for the one hope of restoring peace.",
      trailer: "https://www.youtube.com/watch?v=sGbxmsDFVnE",
      categorgy: "StarWars" ,
    },
    {
      id:8 ,
      title: "Star Wars: Episode VIII - The Last Jedi",
      background:"https://cdn.mos.cms.futurecdn.net/vzatcJE9V7Kk3ktbY5wwJD.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/09B5E23DC281415A7B14D33D4EA08D52A4E74AD6FCB9E6C9FC604AF6910054F4/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: "2017 ‧ Sci-fi/Action ‧ 2h 32m",
      description:"The Star Wars saga continues as new heroes and galactic legends go on an epic adventure, unlocking mysteries of the Force and shocking revelations of the past",
      trailer: "https://www.youtube.com/watch?v=Q0CbN8sfihY",
      categorgy: "StarWars" ,
    },
    {
      id:9 ,
      title: "Star Wars: Episode IX - The Rise of Skywalker",
      background:"https://whatsondisneyplus.com/wp-content/uploads/2019/12/rise-of-skywlkaer.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/57805B4A4CB382D4737B65339AC37B433AAF052C21726B2EB40D1088151BED1E/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: "2019 ‧ Sci-fi/Action  ‧ 2h 21m ",
      description:"In the riveting conclusion of the landmark Skywalker saga, new legends will be born-and the final battle for freedom is yet to come.",
      trailer: "https://www.youtube.com/watch?v=8Qn_spdM5Zg",
      categorgy: "StarWars" ,
    },
    {
      id:10,
      title: "Star Wars : The Mandalorian",
      background:"https://wallpaperaccess.com/full/1726947.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/1C42324412D81E612EFD8E9DAB82B24EB43D057306A3F812214E9BA728DC0162/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: "2019 ‧ Space Western ‧ 3 Seasons ",
      description:"The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
      trailer: "https://www.youtube.com/watch?v=aOC8E8z_ifw",
      categorgy: "StarWars" ,
      recommended: true,
    },
    {
      id:11 ,
      title: "Star Wars : Obi - Wan Kenobi",
      background:"https://techcrunch.com/wp-content/uploads/2022/05/oJ1KKAKiIuBA3s1tvtEa7NlQ2XM.jpg",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/9678FC74FB52573A4F9E8CFEB7E05C930094B1590C1175C530B014E14AA19434/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: "2022 ‧ Adventure ‧ 1 Season ",
      description:"Jedi Master Obi-Wan Kenobi has to save young Leia after she is kidnapped, all the while being pursued by Imperial Inquisitors and his former Padawan, now known as Darth Vader.",
      trailer: "https://www.youtube.com/watch?v=TWTfhyvzTx0",
      categorgy: "StarWars" ,
    },
    {
      id:12 ,
      title: "Star Wars: The Book of Boba Fett",
      background:"https://lumiere-a.akamaihd.net/v1/images/6154816e0b979e0001c347a6-image_f6373620.jpeg?region=0,0,1536,864",
      image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/E77A344BADB816740F2D0863A555D596B249CFCEFF1F8AA85A4A19D2C09078DC/scale?width=1200&aspectRatio=1.78&format=jpeg",
      tags: "2021 ‧ Action fiction ‧ 1 season",
      description:"Bounty hunter Boba Fett and mercenary Fennec Shand navigate the underworld when they return to Tatooine to claim Jabba the Hutt's old turf.",
      trailer: "https://www.youtube.com/watch?v=rOJ1cw6mohw",
      categorgy: "StarWars" ,
    },
    {
        id:13 ,
        title:"Captain America: Civil War",
        background:"https://cdn.mos.cms.futurecdn.net/hjJmqHnszVarJMnKgoKdq5-1200-80.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/FABF318CE0142C2AC915C2D6F9EA63F5ED04F6C907E52D831A0F54476825A62F/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2016 ‧ Action Sci-Fi ‧ 2h 27m",
        description:"Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man.",
        trailer:"https://www.youtube.com/watch?v=dKrVegVI0Us",
        categorgy: "Marvel" ,
    },
    {
        id:14 ,
        title:"Doctor Strange",
        background:"https://www.hollywoodreporter.com/wp-content/uploads/2022/04/SSD1080_comp_v198.1074-H-2022.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/78BE4ABDBE00642AE6D6709FDD14AC6D7D816095752ECF13D3C9642AEA7B88C4/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2016 ‧ Action/Adventure ‧ 1h 55m",
        description:"While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
        trailer:"https://www.youtube.com/watch?v=Lt-U_t2pUHI",
        categorgy: "Marvel" ,
        recommended: true,
    },
    {
        id:15 ,
        title:"Guardians of the Galaxy",
        background:"https://images.thedirect.com/media/article_full/guardians-galaxy-mcu.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/F968B82BEA42F23007EB590619340EC332DFB3126AFC7FED7C3BFEB63AC5144A/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2014 ‧ Action Adventure Comedy ‧ 2h 1m",
        description:"A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
        trailer:"https://www.youtube.com/watch?v=d96cjJhvlMA",
        categorgy: "Marvel" ,
    },
    {
        id:2 ,
        title:"Spider-Man: Homecoming",
        background:"https://cdn.mos.cms.futurecdn.net/QXKcFLFHW8iXZQ9nsQDhd7-1200-80.jpg",
        image:"https://whatsondisneyplus.com/wp-content/uploads/2023/01/spiderman-homcoming.jpg",
        tags:"2017 ‧ Action Adventure Sci-Fi ‧ 2h 13m",
        description:"Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.",
        trailer:"https://www.youtube.com/watch?v=rk-dF1lIbIg",
        categorgy: "Marvel" ,
        recommended: true,
    },
    {
        id:17 ,
        title:"Black Panther ",
        background:"https://gh.cdn.sewest.net/assets/ident/pulse/59756537/TRM-Outfit-BlackPanther-MCUSoloMovie-1920x1080-TG-Final-5twmvcedw.jpg?quality=65",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/E9C4697F1745DEF68CD73B638BE6FCFB72B537788FB4F252E04B7BB745EE27A9/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2018 ‧ Action Adventure Sci-Fi ‧ 2h 14m",
        description:"T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
        trailer:"https://www.youtube.com/watch?v=xjDjIWPwcPU",
        categorgy: "Marvel" ,
    },
    {
        id:18 ,
        title:"Avengers: Infinity War",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/6E9A372F451B9BFE61D81FF9089214CA4F1F57CEF305E55D40E77D1E636C4F91/scale?width=2880&aspectRatio=1.78&format=jpeg",
        image:"https://lumiere-a.akamaihd.net/v1/images/p_incredible_hero_avengers_generic_929a1218.jpeg?region=0,0,1920,800",
        tags:"2018 ‧ Action Adventure Sci-Fi ‧ 2h",
        description:"The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
        trailer:"https://www.youtube.com/watch?v=6ZfuNTqbHE8",
        categorgy: "Marvel" ,
    },
    {
        id:19 ,
        title:"Spider-Man: No Way Home ",
        background:"https://i.ytimg.com/vi/0aIR2oe6h-Y/maxresdefault.jpg",
        image:"https://commentaryboxsports.com/wp-content/uploads/2022/03/Is-Spider-Man-No-Way-Home-Coming-to-Disney-Plus.jpg",
        tags:"2021 ‧ Action Adventure ‧ 2h 28m",
        description:"With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
        trailer:"https://www.youtube.com/watch?v=JfVOs4VSpmA",
        categorgy: "Marvel" ,
        recommended: true,
    },
    {
        id:7 ,
        title:"Avengers: Endgame",
        background:"https://images.hdqwalls.com/wallpapers/disney-plus-avengers-endgame-4k-jv.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/863E75A035911DBA10F8D7EE1E433A12A1BF4915670B66597AC31C585A291942/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2019 ‧ Action Adventure Drama ‧ 3h 1m",
        description:"After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
        trailer:"https://www.youtube.com/watch?v=TcMBFSGVi1c",
        categorgy: "Marvel" ,
        recommended: true,
    },
    {
        id:21 ,
        title:"Frozen",
        background:"https://4kwallpapers.com/images/wallpapers/frozen-elsa-disney-princess-animation-4480x2520-5072.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/5A04BBDD5CFD81AAD009775FE215D3DD8EE604E161603EF230644143815F2A81/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2013 ‧ Animation Adventure Comedy 1h 42m",
        description:"When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.",
        trailer:"https://www.youtube.com/watch?v=TbQm5doF_Uc",
        categorgy: "Disney" ,
    },
    {
        id:22 ,
        title:"The Lion King",
        background:"https://i.pinimg.com/originals/b4/2b/5e/b42b5eb21099ccfbe4af5076f0e40a85.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/0C33CB391625A18FB4A6E08B51231F96062793E521D0AAB42067789B01F39280/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"1994 ‧ Animation Adventure Drama ‧ 1h 28m",
        description:"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
        trailer:"https://www.youtube.com/watch?v=lFzVJEksoDY",
        categorgy: "Disney" ,
    },
    {
        id:23 ,
        title:"Dinosaur",
        background:"https://allears.net/wp-content/uploads/2020/04/disney-plus-dinosaur.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/2DA33A636D572B67D43F53D38600382061E5EF334597BD843E22E6157A03AB6F/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2000 ‧ Adventure/Family ‧ 1h 22m",
        description:"An orphaned dinosaur raised by lemurs joins an arduous trek to a sanctuary after a meteorite shower destroys his family home.",
        trailer:"https://www.youtube.com/watch?v=vZnBR4SDIEs",
        categorgy: "Disney" ,
    },
    {
        id:24 ,
        title:"Mulan",
        background:"https://images.immediate.co.uk/production/volatile/sites/3/2019/05/MLAN2_mu2_sg56p_L-08969e4.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/D100BB6C7CB31A1C80CD1D023BC5827FA539DCA9AC1099B82788CEBE4965C0E6/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"1998 ‧ Animation Adventure Comedy ‧ 1h 27m",
        description:"To save her father from death in the army, a young maiden secretly goes in his place and becomes one of China's greatest heroines in the process.",
        trailer:"https://www.youtube.com/watch?v=HKH7_n425Ss",
        categorgy: "Disney" ,
    },
    {
        id:25 ,
        title:"Lilo & Stitch",
        background:"https://hips.hearstapps.com/digitalspyuk.cdnds.net/17/04/1485279080-lilo-and-stitch.jpg",
        image:"https://static1.srcdn.com/wordpress/wp-content/uploads/2020/03/Lilo-and-Stitch-Disney-changes.jpg",
        tags:"2002 ‧ Family/Comedy ‧ 1h 25m",
        description:"A young and parentless girl adopts a 'dog' from the local pound, completely unaware that it's supposedly a dangerous scientific experiment that's taken refuge on Earth and is now hiding from its creator and those who see it as a menace.",
        trailer:"https://www.youtube.com/watch?v=9OAC55UWAQs",
        categorgy: "Disney" ,
    },
    {
        id:26 ,
        title:"Beauty and the Beast",
        background:"https://rare-gallery.com/mocahbig/72755-Beauty-And-The-Beast-1991-HD-Wallpaper.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/54FDB59A9E6E553E5A62E6B9A09028F18AF39AB2900505E1CE15CAF746DCAD0E/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"1991 ‧ Musical/Fantasy ‧ 1h 24m",
        description:"A prince cursed to spend his days as a hideous monster sets out to regain his humanity by earning a young woman's love.",
        trailer:"https://www.youtube.com/watch?v=iurbZwxKFUE",
        categorgy: "Disney" ,
    },
    {
        id:27 ,
        title:"Tarzan",
        background:"https://i0.wp.com/fullcirclecinema.com/wp-content/uploads/2020/05/tarzandisney3905.jpg?fit=1920%2C1080&ssl=1",
        image:"https://whatsondisneyplus.com/wp-content/uploads/2020/06/Tarzan.jpg",
        tags:"1999 ‧ Adventure/Romance ‧ 1h 28m",
        description:"A man raised by gorillas must decide where he really belongs when he discovers he is a human.",
        trailer:"https://www.youtube.com/watch?v=ie53R2HEZ6g",
        categorgy: "Disney" ,
    },
    {
        id:28 ,
        title:"Aladdin",
        background:"https://m.media-amazon.com/images/M/MV5BMTgzNDI3ODUyMV5BMl5BanBnXkFtZTgwNDg4MjY5NzE@._V1_.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/5A74223BC7390B74F0A3AA140373C8CC49FCB54237FC7C459F943F06EDABC467/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"1992 ‧ Musical/Family ‧ 1h 30m",
        description:"A kindhearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.",
        trailer:"https://www.youtube.com/watch?v=eTjHiQKJUDY",
        categorgy: "Disney" ,
    },
    {
        id:29 ,
        title:"Lightyear",
        background:"https://cdn.mos.cms.futurecdn.net/WanmQg9ctVZXewPa4zb7Nm.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/29859918D787A9A644D348B59AB90854C58DFD65DE68C50B9FBA28C423405167/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2022 ‧ Family/Sci-fi ‧ 1h 45m",
        description:"While spending years attempting to return home, marooned Space Ranger Buzz Lightyear encounters an army of ruthless robots commanded by Zurg who are attempting to steal his fuel source.",
        trailer:"https://www.youtube.com/watch?v=BwZs3H_UN3k",
        categorgy:"Pixar" ,
    },
    {
        id:30 ,
        title:"Toy Story 4",
        background:"https://media-cldnry.s-nbcnews.com/image/upload/newscms/2019_25/2905636/190621-toy-story-4-ew-1138a.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/97773D3AD23DD9942EE4EDDB26E775D192E7AC6B038E459A6CF91D0107BB33AF/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2019 ‧ Family/Adventure ‧ 1h 40m",
        description:`When a new toy called "Forky" joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.`,
        trailer:"https://www.youtube.com/watch?v=wmiIUN-7qhE",
        categorgy:"Pixar" ,
    },
    {
        id:31 ,
        title:"Incredibles 2",
        background:"https://media.newyorker.com/photos/5b23e1b240328426ed9a8b49/16:9/w_2064,h_1161,c_limit/Lane-Incredibles-2.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/FE13ED0824D296424A0DFF86383F034D7D6C0A98365B13ED06DD7B978B25E6B3/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2018 ‧ Family/Adventure ‧ 2h 6m",
        description:"The Incredibles family takes on a new mission which involves a change in family roles: Bob Parr (Mr. Incredible) must manage the house while his wife Helen (Elastigirl) goes out to save the world.",
        trailer:"https://www.youtube.com/watch?v=i5qOzqD9Rms",
        categorgy:"Pixar" ,
    },
    {
        id:32 ,
        title:"Monsters, Inc.",
        background:"https://cdn.vox-cdn.com/thumbor/4Xz-znF2w-mucKPF5L1WSycHE48=/1400x788/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/16019170/Mike_Sulley_Boo_monsters_inc.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/AFB43D8062ABDB29DF18E323CF803AAA33BCCF5F754B12CEEBDAC881DE72155E/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2001 ‧ Animation Adventure Comedy ‧ 1h 32m",
        description:"In order to power the city, monsters have to scare children so that they scream. However, the children are toxic to the monsters, and after a child gets through, two monsters realize things may not be what they think.",
        trailer:"https://www.youtube.com/watch?v=CGbgaHoapFM",
        categorgy:"Pixar" ,
    },
    {
        id:33 ,
        title:"Brave",
        background:"https://www.intofilm.org/intofilm-production/1341/scaledcropped/3000x1688/resources/1341/brave-ep-disney.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/8C1BA16AED00C6E7B67B688E1146CA245698169FE4FDB0B3E0CCF4273E83B47E/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2012 ‧ Animation Adventure Comedy ‧ 1h 33m",
        description:"Determined to make her own path in life, Princess Merida defies a custom that brings chaos to her kingdom. Granted one wish, Merida must rely on her bravery and her archery skills to undo a beastly curse.",
        trailer:"https://www.youtube.com/watch?v=5fPmKfcaaWk",
        categorgy:"Pixar" ,
    },
    {
        id:34 ,
        title:"WALL-E",
        background:"https://wallpaperaccess.com/full/1291994.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/5669753D6F71EB5668B6854BC1EB36BA99217B3EC1D4211EC37A894B6F654AD6/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2008 ‧ Animation Adventure ‧ Family",
        description:"In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
        trailer:"https://www.youtube.com/watch?v=CZ1CATNbXg0",
        categorgy:"Pixar" ,
    },
    {
        id:35 ,
        title:"Ratatouille",
        background:"https://variety.com/wp-content/uploads/2007/06/rexfeatures_1622528a.jpg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/69F9436F08D1FA3FAD59F13B1AA8A7D0C7BABB2CF2FC227741FDBF6387D76F10/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2007 ‧ Animation Adventure Comdedy ‧ 1h 51m",
        description:"A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.",
        trailer:"https://www.youtube.com/watch?v=NgsQ8mVkN8w",
        categorgy:"Pixar" ,
    },
    {
        id:36 ,
        title:"Finding Nemo",
        background:"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/finding-nemo-theory-1623752052.jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/A6B8580D6192BB96B408A8CFFC1A338B933FBC446A10B56349DE7F9CB51C4EDE/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2003 ‧ Animation Adventure Comdedy ‧ 1h 40m",
        description:"After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
        trailer:"https://www.youtube.com/watch?v=9oQ628Seb9w&t=2s",
        categorgy:"Pixar",
    },
    {
        id:37 ,
        title:"Man vs Puma",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/87AA94F4BF88272C697F40C56626E44592DEDC26DEDF9F689FA0C60D6A6F3C15/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/47DCBEDC24DC7A15A97A0F27B0805E8F88F1B79F1613890FA096B60103632B1D/scale?width=400&aspectRatio=1.78&format=jpeg",
        tags:" 2018 ‧ Documentary Animals & Nature ‧ 43m   ",
        description:"Big cat expert Boone Smith travels to Patagonia to observe pumas thriving in the wild under increased conservation efforts; the cats have not learned to fear humans, making this the one place where people can observe their behavior up close.",
        trailer:"https://www.youtube.com/watch?v=oc8vpx_ARRQ&t=14s",
        categorgy:"NationalGeo" ,
    },
    {
        id:38 ,
        title:"Ocean's Weirdest",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/F5CC3480D72770B505BA993F5A101127E4AAADC29CEE544B0C2309F9EB5268A1/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/5FD7F7902D1F7697B5F7BFBA3AF0F5A896EF18BC86AE7BD1778C667D6CA5AD66/scale?width=400&aspectRatio=1.78&format=jpeg",
        tags:"2022 ‧ Docuseries Animals & Nature ‧ 1 Season   ",
        description:"The filmmaker delves into the distinct behavioural patterns exhibited by ocean creatures during their attempts to survive, mate and adapt to their surroundings.",
        trailer:"https://www.youtube.com/watch?v=8PDj22hFow8",
        categorgy:"NationalGeo" ,
    },
    {
        id:39 ,
        title:"Limitless with Chris Hemsworth",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/C77C92E99CDF98F1BE4BD8BE48ADF9AFA2639AA3AA925E7896C457147139E576/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/B99E52F5905E1F40B27458CCDC0D3608AA83D92DF917795BCA1C49EB5E939091/badging?width=400&aspectRatio=1.78&format=jpeg&label=disneyplusoriginal",
        tags:" 2022 ‧ Docuseries, Lifestyle, Action-Adventure ‧ 1 Season ",
        description:"Chris Hemsworth explores the different ways humans can live better for longer by taking on physical challenges such as diving in ice or climbing skyscrapers.",
        trailer:"https://www.youtube.com/watch?v=4AxfL9Y4boE",
        categorgy:"NationalGeo" ,
    },
    {
        id:40 ,
        title:"The Flagmakers",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/A9A6D8D4224161EA27DDF6EA44E971E29E0BEC8AF075AC8C5D90A9D159F4AE5A/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/6EF900C92ABC5D61EBDAD274E9C6923AA0FFFCA02A31DC8BC732DEC09712236E/badging?width=400&aspectRatio=1.78&format=jpeg&label=disneyplusoriginal",
        tags:"2022 ‧ Documentary ‧ 35m ",
        description:"a meditation on the American dream, follows workers at the country’s largest manufacturer of American flags and flagpoles, including the refugees and immigrants who have risked everything to come to the USA.",
        trailer:"https://www.youtube.com/watch?v=QKCN_ppi2yw",
        categorgy:"NationalGeo" ,
    },
    {
        id:41 ,
        title:"Victoria Falls Africa's Garden of Eden",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/0D0B1B56771EBB9AE68BC2296496CBECA20901B34A47A34AD9685DE50A596E70/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/A9EB68517A07D3CDF22CAF1F3B39ADE466280CDFE7A5BF2F1C9308809EF2CDC1/scale?width=400&aspectRatio=1.78&format=jpeg",
        tags:"2021 ‧ Documentary, Animals & Nature ‧ 44m ",
        description:"One can see them from distances up to 30km: Like a mumbling, bubbling volcano, ready to erupt, a glowing cloud rises from the earth.",
        trailer:"https://www.youtube.com/watch?v=gdtfjm1peDc",
        categorgy:"NationalGeo" ,
    },
    {
        id:42 ,
        title:"Super/Natural",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/E1994F4FE352A821CCCB5BC58A99C7C0597ABBEBE3B5CC17A756E5BC2D582F50/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/7F7FB344FE9EEE6780F30625CDE0F5FADA4562D3C0F9D4B6545378232BE5D1B4/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2022 ‧ Docuseries, Animals & Nature ‧ 1 Season  ",
        description:"Witness the secret powers of extraordinary animals, experience the world as they do and see the SUPER/NATURAL side of nature as never before. This title is executive produced by James Cameron and narrated by Benedict Cumberbatch",
        trailer:"https://www.youtube.com/watch?v=GDYEVR12aoE",
        categorgy:"NationalGeo" ,
    },
    {
        id:43 ,
        title:"Welcome to Earth",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/8C7DB3DB50EE3CBF59C7098B533DF09BA881D85EF4E4CDCD72F525D9B765C3FD/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://i.ytimg.com/vi/WUHbPgbFq14/maxresdefault.jpg ",
        tags:"2021 ‧ Family, Docuseries, Animals & Nature ‧ 1 Season   ",
        description:"The Disney+ orignal series from National Geographic follows Will Smith on an extraordinary adventure around the world to explore Earth's greatest wonders and reveal its most hidden secrets. Throughout the six-part limited series produced by filmmaker Darren Aronofsky, Protozoa Pictures, Jane Root's Nutopia and Westbrook Stuidios, Will is guided by elite explorers on an awe-inspiring journey",
        trailer:"https://www.youtube.com/watch?v=i0MTCXgil1M",
        categorgy:"NationalGeo",
    },
    {
        id:44 ,
        title:"America The Beautiful",
        background:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/22CEA5694B661AB902F0A18C7F407F99874FE437E481220A4C9AB05977160BB5/scale?width=1440&aspectRatio=1.78&format=jpeg",
        image:"https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/70E7D8FF6400585D0D0A95698CD99CEB7B800C32C162D2E123D5706B96888201/scale?width=1200&aspectRatio=1.78&format=jpeg",
        tags:"2022 ‧ Docuseries, Animals & Nature ‧ 1 Season  ",
        description:"North America and its wildlife as you've never seen them before - heroic animals, new animal behavior and breath-taking landscape visuals",
        trailer:"https://www.youtube.com/watch?v=p8jYJQzcKpY",
        categorgy:"NationalGeo",
    }
    
    
  ];